### ISSUE TITLE
Wrong parent class for ActivityOfPathologicalProcess

### ISSUE THREAD

**Issue by 15E601** [RDFBones/Standards-Pathologies#1] opened 2023-03-24 12:34 UTC
When generating the Phaleron App Ontology with Robot, the class  **http://w3id.org/rdfbones/ext/standards-patho/ActivityOfPathologicalProcess** becomes a subclass of **http://w3id.org/rdfbones/ext/standards-patho/ActivityOfPathologicalProcessValueSpecification**
I do not see any errors in the templates, so perhaps an error in the Robot script?

**Comment by cuboideum** [comment] 2023-12-08 10:20
This is a duplicate of https://github.com/RDFBones/RDFBones-O/issues/199.

**Closed as completed by cuboideum** 2023-12-08 10:20 UTC
Labels: bug
